# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

defaults: &defaults
  environment:
    CI_SCRIPTS: "npx --quiet --package @reactioncommerce/ci-scripts@1.6.2"
    DOCKER_REPOSITORY: "reactioncommerce/kinetic"
    DOCKER_NAMESPACE: "reactioncommerce"
    DOCKER_NAME: "kinetic"
  docker:
    - image: circleci/node:14.18.1-stretch

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2

jobs:
  install-pnpm:
    <<: *defaults
    steps:
      - run:
          name: Install pnpm
          command: sudo npm install -g pnpm
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install NPM dependencies
          command: pnpm install

  eslint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Lint JavaScript
          command: pnpm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies
      - install-pnpm
      - eslint:
          requires:
            - install-pnpm
            - install-dependencies

